# Generated by Django 4.2.16 on 2024-10-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('learn_more_url', models.TextField()),
                ('location', models.CharField(blank=True, max_length=255)),
                ('more_locations', models.CharField(blank=True, max_length=255)),
                ('experience_level', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
