# Generated by Django 4.2.16 on 2024-10-12 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='job',
            table='google_job_table',
        ),
    ]
